# Generated by Django 5.2.2 on 2025-06-28 13:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('texte', django_ckeditor_5.fields.CKEditor5Field()),
                ('texte_bouton', models.CharField(default='Commencer maintenant', max_length=100)),
                ('lien_bouton', models.URLField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Appel à l'action",
                'verbose_name_plural': "Appels à l'action",
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('annee', models.CharField(max_length=9)),
                ('objectif_global', models.DecimalField(decimal_places=2, default=0, help_text='Objectif total à atteindre pour cette cotisation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('est_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom ou description du logo', max_length=100)),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Fichier logo (SVG, PNG, etc.)')),
                ('actif', models.BooleanField(default=False, help_text='Définit si ce logo est utilisé actuellement')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-actif', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='MessageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre principal en haut de la page d'accueil", max_length=200)),
                ('sous_titre', django_ckeditor_5.fields.CKEditor5Field()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Message d'accueil",
                'verbose_name_plural': "Messages d'accueil",
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.TextField(blank=True, help_text='Permissions spéciales pour ce rôle (JSON)')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SectionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Notre mission de solidarité', max_length=200)),
                ('description', models.TextField()),
                ('est_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Section - Mission',
                'verbose_name_plural': 'Section - Mission',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lien_avec_enfant', models.CharField(blank=True, default='Anonyme', help_text='Ex : Père, Mère, Grand frère, Tuteur...', max_length=100)),
                ('message', models.TextField()),
                ('nombre_etoiles', models.PositiveSmallIntegerField(default=5)),
                ('est_visible', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_decede', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', help_text="Sexe de l'enfant", max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enfants/photos/')),
                ('membre_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='gestion.membre')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('RAPPEL', 'Rappel de paiement'), ('VALIDATION', 'Validation de paiement'), ('ANNONCE', 'Annonce générale')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ParametrageCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_cotisation_libre', models.BooleanField(default=True, help_text='Si coché, les membres peuvent choisir le montant à verser')),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, help_text='Si la cotisation est fixe, indiquez le montant que chaque membre doit verser.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_minimum', models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum pour les cotisations libres', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('accepter_paiement_partiel', models.BooleanField(default=True, help_text='Autoriser les paiements partiels')),
                ('cotisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('validee', models.BooleanField(default=False)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
                ('moyen_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.moyenpaiement')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to='gestion.membre')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RappelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rappel', models.DateTimeField(auto_now_add=True)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message_personnalise', models.TextField(blank=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
            ],
            options={
                'ordering': ['-date_rappel'],
            },
        ),
        migrations.CreateModel(
            name='PointMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gestion.sectionmission')),
            ],
            options={
                'verbose_name': 'Point clé de mission',
                'verbose_name_plural': 'Points clés de mission',
            },
        ),
        migrations.CreateModel(
            name='ObjectifNiveauCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.niveauscolaire')),
            ],
            options={
                'unique_together': {('niveau', 'cotisation')},
            },
        ),
        migrations.CreateModel(
            name='MembreRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.role')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('membre', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ScolariteEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(help_text='Format obligatoire : 2023-2024', max_length=9)),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.enfant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.niveauscolaire')),
            ],
            options={
                'ordering': ['-annee', 'niveau__ordre'],
                'unique_together': {('enfant', 'annee')},
            },
        ),
    ]
