# Generated by Django 5.2.2 on 2025-06-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9)),
                ('objectif_global', models.DecimalField(decimal_places=2, default=0, help_text='Objectif total à atteindre pour cette cotisation', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('est_decede', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('membre_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='gestion.membre')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectifNiveauCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.niveauscolaire')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrageCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_cotisation_libre', models.BooleanField(default=True)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, help_text='Si la cotisation est fixe, indiquez le montant que chaque membre doit verser.', max_digits=12, null=True)),
                ('cotisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('validee', models.BooleanField(default=False)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
                ('moyen_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.moyenpaiement')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements_valides', to='gestion.membre')),
            ],
        ),
        migrations.CreateModel(
            name='MembreRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.role')),
            ],
            options={
                'unique_together': {('membre', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ScolariteEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.enfant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.niveauscolaire')),
            ],
            options={
                'unique_together': {('enfant', 'niveau', 'annee')},
            },
        ),
    ]
