# Generated by Django 4.2.16 on 2025-06-06 23:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisation',
            options={'ordering': ['-annee']},
        ),
        migrations.AlterModelOptions(
            name='enfant',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AlterModelOptions(
            name='membreroles',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AlterModelOptions(
            name='moyenpaiement',
            options={'ordering': ['libelle']},
        ),
        migrations.AlterModelOptions(
            name='niveauscolaire',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='payement',
            options={'ordering': ['-date_paiement']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='scolariteenfant',
            options={'ordering': ['-annee', 'niveau__ordre']},
        ),
        migrations.AddField(
            model_name='cotisation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enfant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='enfants/photos/'),
        ),
        migrations.AddField(
            model_name='enfant',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres/photos/'),
        ),
        migrations.AddField(
            model_name='membre',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membreroles',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membreroles',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='parametragecotisation',
            name='accepter_paiement_partiel',
            field=models.BooleanField(default=True, help_text='Autoriser les paiements partiels'),
        ),
        migrations.AddField(
            model_name='parametragecotisation',
            name='montant_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum pour les cotisations libres', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.TextField(blank=True, help_text='Permissions spéciales pour ce rôle (JSON)'),
        ),
        migrations.AddField(
            model_name='scolariteenfant',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='objectif_global',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Objectif total à atteindre pour cette cotisation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='objectifniveaucotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='parametragecotisation',
            name='est_cotisation_libre',
            field=models.BooleanField(default=True, help_text='Si coché, les membres peuvent choisir le montant à verser'),
        ),
        migrations.AlterField(
            model_name='parametragecotisation',
            name='montant_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si la cotisation est fixe, indiquez le montant que chaque membre doit verser.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='payement',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to='gestion.membre'),
        ),
        migrations.AlterUniqueTogether(
            name='objectifniveaucotisation',
            unique_together={('niveau', 'cotisation')},
        ),
        migrations.CreateModel(
            name='RappelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rappel', models.DateTimeField(auto_now_add=True)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message_personnalise', models.TextField(blank=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
            ],
            options={
                'ordering': ['-date_rappel'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('RAPPEL', 'Rappel de paiement'), ('VALIDATION', 'Validation de paiement'), ('ANNONCE', 'Annonce générale')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
