# Generated by Django 5.2.2 on 2025-06-28 16:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scolariteenfant',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectifniveaucotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
