# Generated by Django 5.2.2 on 2025-06-09 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_cotisation_options_alter_enfant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('texte', ckeditor.fields.RichTextField()),
                ('texte_bouton', models.CharField(default='Commencer maintenant', max_length=100)),
                ('lien_bouton', models.URLField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Appel à l'action",
                'verbose_name_plural': "Appels à l'action",
            },
        ),
        migrations.CreateModel(
            name='MessageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre principal en haut de la page d'accueil", max_length=200)),
                ('sous_titre', ckeditor.fields.RichTextField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Message d'accueil",
                'verbose_name_plural': "Messages d'accueil",
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('message', ckeditor.fields.RichTextField()),
                ('actif', models.BooleanField(default=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_publication'],
            },
        ),
    ]
