# Generated by Django 5.2.2 on 2025-06-28 17:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_scolariteenfant_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifniveaucotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
