# Generated by Django 5.2.2 on 2025-06-09 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_appelaction_messageaccueil_temoignage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Notre mission de solidarité', max_length=200)),
                ('description', models.TextField()),
                ('est_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Section - Mission',
                'verbose_name_plural': 'Section - Mission',
            },
        ),
        migrations.CreateModel(
            name='PointMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gestion.sectionmission')),
            ],
            options={
                'verbose_name': 'Point clé de mission',
                'verbose_name_plural': 'Points clés de mission',
            },
        ),
    ]
