# Generated by Django 5.2.2 on 2025-06-10 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_sectionmission_pointmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temoignage',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='temoignage',
            old_name='auteur',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='date_publication',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='role',
        ),
        migrations.AddField(
            model_name='temoignage',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='est_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='lien_avec_enfant',
            field=models.CharField(blank=True, default='Anonyme', help_text='Ex : Père, Mère, Grand frère, Tuteur...', max_length=100),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='nombre_etoiles',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temoignages/photos/'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='message',
            field=models.TextField(),
        ),
    ]
