# Generated by Django 5.2.2 on 2025-06-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_temoignage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temoignage',
            name='photo',
        ),
    ]
