# Generated by Django 5.2.2 on 2025-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_scolariteenfant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scolariteenfant',
            name='annee',
            field=models.CharField(help_text='Format obligatoire : 2023-2024', max_length=9),
        ),
    ]
