# Generated by Django 5.2.2 on 2025-06-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_scolariteenfant_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', help_text="Sexe de l'enfant", max_length=1),
        ),
    ]
