# Generated by Django 5.2.2 on 2025-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_enfant_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom ou description du logo', max_length=100)),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Fichier logo (SVG, PNG, etc.)')),
                ('actif', models.BooleanField(default=False, help_text='Définit si ce logo est utilisé actuellement')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-actif', '-date_ajout'],
            },
        ),
    ]
